name: relevant
version: 0.1.0.0
dependencies:
- aeson
- aeson-qq
- base
- bloodhound
- bytestring
- http-client
- http-conduit
- pretty-simple
- text
- unordered-containers
- vector
ghc-options:
- -Wall
executables:
  relevant:
    source-dirs: src
    main: Main.hs
