name: relevant
version: 0.1.0.0
dependencies:
- aeson
- base
- bloodhound
- bytestring
- http-client
- text
- unordered-containers
ghc-options:
- -Wall
executables:
  relevant:
    source-dirs: src
    main: Main.hs
